spring:
  application:
    name: votacao-pauta
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/votacao_pauta
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
          show_sql: false
          use_sql_comments: true
          fomart_sql: true
URL: "https://user-info.herokuapp.com/users/{cpf}"