CREATE TABLE SCHEDULE (
    ID                   INTEGER NOT NULL AUTO_INCREMENT,
    DESCRICAO            VARCHAR(255),
    PRIMARY KEY(ID)
);

CREATE TABLE ASSOCIATED (
    ID                   INTEGER NOT NULL AUTO_INCREMENT,
    ASSOCIATED_CPF       VARCHAR(255),
    SCHEDULE_ID          INTEGER,
    PRIMARY KEY (ID),
    FOREIGN KEY (SCHEDULE_ID) REFERENCES SCHEDULE(ID)
);

CREATE TABLE VOTING_SESSION (
    ID                   INTEGER NOT NULL AUTO_INCREMENT,
    DATE_TIME_START      TIMESTAMP,
    DATE_TIME_END        TIMESTAMP,
    ACTIVE               TINYINT(1),
    PRIMARY KEY (ID)
);

CREATE TABLE VOTING (
    ID                   INTEGER NOT NULL AUTO_INCREMENT,
    VOTE                 TINYINT(1),
    SCHEDULE_ID          INTEGER,
    VOTING_SESSION_ID    INTEGER,
    PRIMARY KEY (ID),
    FOREIGN KEY (SCHEDULE_ID) REFERENCES SCHEDULE(ID),
    FOREIGN KEY (VOTING_SESSION_ID) REFERENCES VOTING_SESSION(ID)

);
