CREATE TABLE SCHEDULE (
    ID                   INTEGER NOT NULL,
    DESCRICAO            VARCHAR2(255 CHAR)
);

ALTER TABLE SCHEDULE ADD CONSTRAINT SCHEDULE_PK PRIMARY KEY (ID);

CREATE TABLE ASSOCIATED (
    ID                   INTEGER NOT NULL ,
    ASSOCIATED_CPF       VARCHAR2(255 CHAR),
    SCHEDULE_ID          INTEGER
);

ALTER TABLE ASSOCIATED ADD CONSTRAINT ASSOCIATED_PK PRIMARY KEY (ID);

ALTER TABLE ASSOCIATED ADD CONSTRAINT ASSOCIATED_FK  FOREIGN KEY (SCHEDULE_ID) REFERENCES SCHEDULE(ID);

CREATE TABLE VOTING_SESSION (
    ID                   INTEGER NOT NULL ,
    DATE_TIME_START      TIMESTAMP WITH TIME ZONE,
    DATE_TIME_END        TIMESTAMP WITH TIME ZONE,
    ACTIVE               NUMBER(1)
);

ALTER TABLE VOTING_SESSION ADD CONSTRAINT VOTING_SESSION_PK PRIMARY KEY (ID);

CREATE TABLE VOTING (
    ID                   INTEGER NOT NULL ,
    VOTE                 NUMBER(1),
    SCHEDULE_ID          INTEGER,
    VOTING_SESSION_ID    INTEGER
);

ALTER TABLE VOTING ADD CONSTRAINT VOTING_PK PRIMARY KEY (ID);

ALTER TABLE VOTING ADD CONSTRAINT SCHEDULE_ID_FK  FOREIGN KEY (SCHEDULE_ID) REFERENCES SCHEDULE(ID);

ALTER TABLE VOTING ADD CONSTRAINT VOTING_SESSION_ID_FK  FOREIGN KEY (VOTING_SESSION_ID) REFERENCES VOTING_SESSION(ID);

CREATE SEQUENCE SCHEDULE_SEQ START WITH 1;
CREATE SEQUENCE ASSOCIATED_SEQ START WITH 1;
CREATE SEQUENCE VOTING_SESSION_SEQ START WITH 1;
CREATE SEQUENCE VOTING_SEQ START WITH 1;
